name: Jsonix tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      
      - name: Install Project Dependencies
        working-directory: ./nodejs/scripts
        run: npm ci
      
      - name: Run test scripts
        working-directory: ./nodejs/scripts
        run: npm run test
